---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Define nodejs_install_npm_user
  set_fact:
    nodejs_install_npm_user: "{{ ansible_ssh_user | default('root') }}"
  when: nodejs_install_npm_user is not defined

- name: Ensure forever is at the latest release.
  npm: name=forever global=yes state=latest
  become: True
#  become_user: "{{ nodejs_install_npm_user }}"
  when: nodejs_forever

- name: Ensure bower is installed.
  npm: name=bower global=yes state=latest
  become: True

- name: Ensure npm global packages are at the latest release.
  npm:
    name: "{{ item.name }}"
    version: "{{ item.version | default('') }}"
    global: yes
    state: latest
  become: True
 # become_user: "{{ nodejs_install_npm_user }}"
  with_items: "{{ nodejs_npm_global_packages }}"
