---
- hosts: all
  become: true
  gather_facts: yes
  roles:
    - nfs
    - packer-debian
    - elixir
    - postgresql
    - nodejs
    - git
    - inotify-tools
  tasks:
    - name: install extra packages
      apt: "name={{ item }} state=installed"
      with_items:
        - wget
        - curl
        - vim
        - build-essential

    - name: set postgres password
      postgresql_user: user=postgres password=postgres
  vars:
    elixir_version: 1.10.2
    elixir_phoenix_user: vagrant
    postgresql_version: 12.2
    nodejs_version: 12.16.1
    phoenix_framework_version: 1.4.14
